
import { ProductCategories } from '@/Sections/Categories/Category'
import Footer from '@/Sections/Footer/Footer'
import { Header } from '@/Sections/Header/Header'

import { HeroCarousel } from '@/Sections/Hero/Hero'
import Head from 'next/head'
import React, { Fragment } from 'react'

const page = () => {
  return (
    <Fragment >
      <Header />
      <div className=''>
        <section className=''> <HeroCarousel /></section>
        <ProductCategories />
      </div>
      <Footer />
    </Fragment>
  )
}

export default page

export const metadata = {
  title: "Home Page - E-Commerce Website",
  description: "Generated by create next app",
};