
import Footer from '@/Sections/Footer/Footer'
import { Header } from '@/Sections/Header/Header'
import Head from 'next/head'
import React, { Fragment } from 'react'

const page = () => {
  return (
    <Fragment>
      <Header />
      <Footer />
    </Fragment>
  )
}

export default page

export const metadata = {
  title: "Home Page - E-Commerce Website",
  description: "Generated by create next app",
};